.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SURSERVER" "1" "October 2011" "" ""
.
.SH "NAME"
\fBsurserver\fR \- subtle user repository
.
.SH "SYNOPSIS"
\fBsurserver\fR
.
.SH "DESCIPTION"
\fBsurserver\fR is the server part of \fBsur\fR, it maintains a repository and allows access to it via http on default port 4567\.
.
.SH "EXAMPLES"
.
.nf

surserver
.
.fi
.
.SH "BUGS"
Report bugs at http://subforge\.org/projects/subtle/issues
.
.br
Homepage: http://subtle\.subforge\.org
.
.SH "COPYRIGHT"
Copyright (c) Christoph Kappel \fIunexist@subforge\.org\fR
.
.SH "SEE ALSO"
sur(1), subtle(1), subtler(1), subtlext(1)
